name: Deploy FSL Challenge App

on:
  push
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "12.x"
      
      - name: Install dependencies
        run: npm install
        
      - name: Linter (ESLint)
        run: npm run lint
      
      - name: Test (Jest) CI=true
        run: npm run test
        
      - name: Build
        run: npm run build
        
      - name: Copy folder content recursively to remote (dev)
        if: github.ref == 'refs/heads/dev'
        uses: garygrossgarten/github-action-scp@release
        with:
          local: "build"
          remote: "/var/www/html"
          host: "18.230.139.57"
          username: "ec2-user"
          privateKey: ${{ secrets.RSA_PRIV_KEY }}

      - name: Copy folder content recursively to remote (stage)
        if: github.ref == 'refs/heads/stage'
        uses: garygrossgarten/github-action-scp@release
        with:
          local: "build"
          remote: "/var/www/html"
          host: "15.228.245.156"
          username: "ec2-user"
          privateKey: ${{ secrets.RSA_PRIV_KEY }}

      - name: Copy folder content recursively to remote (prod)
        if: github.ref == 'refs/heads/prod'
        uses: garygrossgarten/github-action-scp@release
        with:
          local: "build"
          remote: "/var/www/html"
          host: "18.229.162.149"
          username: "ec2-user"
          privateKey: ${{ secrets.RSA_PRIV_KEY }}
